ci:
  trigger:
    include:
      - project: 'todolist-micro-services/pipeline'
        ref: 'master'
        file: 'server/ci.yml'
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
