/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist.jwttoken;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try (BufferedReader reader = new BufferedReader(new FileReader("/Users/pad/delivery/todoList/todolist-database/.env"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split("=");
                if (System.getProperties().containsKey(parts[0])) {
                    System.getProperties().setProperty(parts[0], parts[1]);
                } else {
                    System.setProperty(parts[0], parts[1]);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        String secret = "asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4";
        String name = "John Doe";
        String email = "johndoe@gmail.com";
        String subject = "John";
        int nbrHour = 24;

        JwtTokenType token = JwtToken.createJwtToken(secret, name, email, subject, nbrHour);
        System.out.println(token.getJwtValue());
        System.out.println(token.getJwtValue().length());
        System.out.println(token.getExpirationDate().toString());
    }
}
